### ISSUE TITLE
Loader not working. 

### ISSUE THREAD

**Issue by oconely** [retyui/group-css-media-queries-loader#10]
Hello!
This is my config:
```js
module: {
rules: [
            {
                test: /\.scss$/,
                use: 
                [
                    MiniCssExtractPlugin.loader,
                    {loader: "css-loader", options: {url: false}},
                    "group-css-media-queries-loader",
                    "sass-loader"
                ]
            },
]
}
```

After build resulting css file stay the same - media queries not grouped.

**Comment by retyui** [comment]
@oconely Can you create a demonstration repo to reproduce this bag?

**Comment by artsandiego** [comment]
Hi @oconely , please refer to #1 

Here's my config.

```
// scss
{
  test: /\.(sa|sc|c)ss$/,
  exclude: /node_modules/,
  use: [
    MiniCssExtractPlugin.loader,
    {
      loader: 'css-loader',
      options: {
        url: false,
      },
    },
    {
      loader: 'postcss-loader',
    },
    {
      loader: 'group-css-media-queries-loader',
      options: { sourceMap },
    },
    {
      loader: 'sass-loader',
      options: {
        outputStyle: 'expanded',
      },
    },
  ],
},
```

**Comment by romanran** [comment]
`{
                test: /\.scss$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: MiniCssExtractPlugin.loader, 
                    },
                    {
                        loader: 'css-loader'
                    },
                    {
                        loader: "postcss-loader"
                    },
                                            {
                                                loader: "group-css-media-queries-loader",
                                                options: { sourceMap: true }
                                            },
                    {
                        loader: 'sass-loader',
                        options: {
                            importer: [jsonImporter, globImporter()]
                        }
                    }
                ]
            },
`
Media queries do not merge as well. I'm using vue and scss.
