### ISSUE TITLE
group-css-media-queries: postcss.plugin was deprecated.

### ISSUE THREAD

**Issue by tednaaa** [retyui/group-css-media-queries-loader#11]
![image](https://user-images.githubusercontent.com/79831859/134353075-008a7c39-8fff-4dae-8e05-2ff8c486062d.png)

migration guide - https://evilmartians.com/chronicles/postcss-8-plugin-migration

**Comment by tednaaa** [comment]
trying to fix in #12
all tests is also are passed

**Comment by tednaaa** [comment]
also added script in `package.json` for `clean publishing to npm`

![image](https://user-images.githubusercontent.com/79831859/134361344-4241aa51-c0bd-466c-836f-49db844a3de0.png)

**Comment by retyui** [comment]
Fixed in **4.0.0**

- Diff: https://npmfs.com/compare/group-css-media-queries-loader/3.0.2/4.0.0/
- Changelog https://github.com/retyui/group-css-media-queries-loader/blob/master/CHANGELOG.md#400

**Comment by tednaaa** [comment]
it seems we broke something

![image](https://user-images.githubusercontent.com/79831859/134422136-6b35d0b0-9055-4af9-8896-29ab940849ce.png)

**Comment by retyui** [comment]
@and-bulk please try 4.0.1

**Comment by retyui** [comment]
Good catch! I've added the e2e test to test this issue

fixed in **4.1.0**

**Comment by tednaaa** [comment]
![image](https://user-images.githubusercontent.com/79831859/134466545-cc5df74e-393b-4ba8-b140-fb661b4023f4.png)

what is it used for?

**Comment by retyui** [comment]
I'm using a Typescript for a webpack config file and to define `tsconfig.json` that should use `node-ts` use when compile `ts=>js` I define `TS_NODE_PROJEST` environment variable 

- See docs: https://webpack.js.org/configuration/configuration-languages/#typescript

**Comment by tednaaa** [comment]
it seems we are working on different operating systems. fixed in #16

**Comment by tednaaa** [comment]
getting error:

![image](https://user-images.githubusercontent.com/79831859/134718164-84f1be7e-1987-47d3-92db-94a99b543609.png)
![image](https://user-images.githubusercontent.com/79831859/134718231-23e02931-20a1-4335-ab36-d4d6e74d0a45.png)

but I don't know how to fix that

**Comment by retyui** [comment]
To fix `npm i schema-utils --save-dev`

which version of webpack do you use?

**Comment by tednaaa** [comment]
`"webpack": "^5.52.1",`
`"webpack-cli": "^4.8.0",`

`npm i schema-utils --save-dev` solved the problem, but I didn't get it, shouldn't the plugin itself download its dependencies

**Comment by retyui** [comment]
@tednaaa I agree, in [4.3.0](https://github.com/retyui/group-css-media-queries-loader/blob/master/CHANGELOG.md#430) `schema-utils` added  as dependencies
