### ISSUE TITLE
Sourcemap support

### ISSUE THREAD

**Issue by ilyvion** [retyui/group-css-media-queries-loader#4]
As soon as I added the `group-css-media-queries-loader` to my chain, sourcemap support broke down. I tried adding `options: {sourceMap: true}` to the loader, like you can do on the `sass-loader` and the `css-loader`, but it made no difference.

What has to be done in order for sourcemaps to still work when using this loader?

**Comment by retyui** [comment]
@alexschrod Hi!
The `group-css-media-queries` the module did not support configuration.
I created a temporary wrapper https://github.com/retyui/group-css-media-queries-loader/tree/next, Where did I add support `sourceMap`

### Install
```js
yarn add -D group-css-media-queries-loader@next
# or npm i -D group-css-media-queries-loader@next
```

**Comment by ilyvion** [comment]
Hey, thanks a lot! I was so busy the last couple of days at work that I didn't have time to try it out, but I definitely will as soon as I can.

**Comment by ilyvion** [comment]
Hey, I tested it, and it mostly works, although it seems to get confused when there are two files that share the same name, although that's certainly not the end of the world and it's still much better than it was before.

**Comment by retyui** [comment]
@alexschrod 

>  two files that share the same name

Can you create a test repository with a this problem?
