### ISSUE TITLE
npm package version 3.0.0 does not include the lib folder

### ISSUE THREAD

**Issue by ssougnez** [retyui/group-css-media-queries-loader#7]
Hi,

I just tried to use this package but when I install it via yarn (`yarn add group-css-media-queries-loader -D`), I can't use it as the directory in "node_modules" does not contain the "lib" directory.

I installed the version 2.0.2 and this one does contain it.

Cheers

**Comment by retyui** [comment]
Oh shit. I published a new version `3.0.1` with `./lib` folder!

Thank you @ssougnez!

**Comment by ssougnez** [comment]
Oh boy, that was fast.

I'll open a new issue then :-D

**Comment by retyui** [comment]
No problem
