### ISSUE TITLE
Default options should be used if options are not supplied

### ISSUE THREAD

**Issue by ssougnez** [retyui/group-css-media-queries-loader#8]
Hi,

I currently have the following configuration:

```
{
    test: /\.scss$/,
    use: [
        { loader: MiniCssExtractPlugin.loader },
        { loader: "css-loader" },
        { loader: "postcss-loader", options: { parser: 'sugarss' } },
        { loader: "group-css-media-queries-loader" },
        { loader: "sass-loader" }
    ]
}
```

And when I run webpack", I get the following error:

> TypeError: Cannot read property 'sourceMap' of null

I can fix the issue easily like this:

`{ loader: "group-css-media-queries-loader", options: { sourceMap: false } }`

However, it would be cool to be able not to specify any options, for example, for the people who are using the following syntax:

`use: [MiniCssExtractPlugin.loader, "css-loader", "postcss-loader", "group-css-media-queries-loader", "sass-loader"]`

Currently, the syntax above is not supported.

Cheers

**Comment by retyui** [comment]
Oh, that's a great case. I fixed this problem!

**Comment by ssougnez** [comment]
Man, issues don't stay open very long with you ha ha :+1:

**Comment by retyui** [comment]
These problems are not so complicated

**Comment by ssougnez** [comment]
True.

I just tested it and it works as expected now :+1:
